# Generated by Django 5.0.7 on 2024-08-08 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_uploadedfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
