# Generated by Django 5.1 on 2024-08-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_uploadedfile_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
