# Generated by Django 5.0.7 on 2024-08-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_classname_user_class_name_user_classes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='classes',
            field=models.ManyToManyField(to='users.classname'),
        ),
    ]
