# Generated by Django 5.0.7 on 2024-08-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_uploadedfile_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
