# Generated by Django 5.1 on 2024-08-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_uploadedfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
