// app/layout.js
import { Inter } from 'next/font/google';
import '../app/styles/globals.css';
import Layout from '../app/components/layout';
import { AuthProvider } from '../app/context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Layout>{children}</Layout>
        </body>
      </html>
    </AuthProvider>
  );
}
